# sample_config.yaml

utils:
  seed: 123
  torch_num_threads: 10

task:
  name: 'CG'
  type: CG # type: cdfg or dfg
  target: gpu640 # different target prediction
  processed_folder: '~/DGRL-Hardware/data_processed/'
  divide_seed: default #set as default or a seed
  raw_data_path: '~/DGRL-Hardware/data_raw/CG/'
  data_processor: CGDataProcessor

train:
  batch_size: 512
  epoch: 500
  optimizer: Adam
  scheduler: 
    name: StepLR
    step_size: 100
    gamma: 0.95
  lr : 0.008053104451157452
  criterion: MSE
  wandb: 0
  train_files: '~/DGRL-Hardware/train_files/'
  directed: 1

model: 
  name: DIGCN
  hidden_dim: 204
  num_layers: 5
  node_input_dim: 7
  edge_input_dim: 2
  dropout: 0.2
  mlp_out:
    num_layer: 4