# for HLS hidden_dim: [4,15]
name: BIGINE
hidden_dim: [1,3]
num_layers: [2,5]
# for HLS lr: [1e-4, 5e-3]
lr: [1e-4, 1e-2]
batch_size: [32, 64]
dropout: [0, 0.1, 0.2, 0.3]
# for HLS node_input_dim: 7
pe_dim_input: 32
pe_dim_output: 8

mlp_out:
  num_layer: [2,4]