# sample_config.yaml

utils:
  seed: 123
  torch_num_threads: 10

task:
  name: 'TIME'
  type: TIME # type: cdfg or dfg
  target: setup # different target prediction
  processed_folder: '~/DGRL-Hardware/data_processed/'
  divide_seed: default #set as default or a seed
  raw_data_path: '~/DGRL-Hardware/data_raw/TIME/'
  data_processor: TIMEDataProcessor

train:
  batch_size: 1
  epoch: 1000
  optimizer: Adam
  scheduler: 
    name: StepLR
    step_size: 100
    gamma: 0.95
  lr : 0.0006380063655102206
  criterion: MSE
  wandb: 0
  train_files: '~/DGRL-Hardware/train_files/'
  directed: 0

model: 
  name: GAT
  hidden_dim: 96
  num_layers: 7
  node_input_dim: 7
  edge_input_dim: 2
  dropout: 0
  mlp_out:
    num_layer: 4