[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "DGRL-Hardware"
authors = [{name = "Graph-COM", email = ""}]
dynamic = ["version", "description"]
