# sample_config.yaml

utils:
  seed: 123
  torch_num_threads: 10

task:
  name: 'HLS'
  type: cdfg # type: cdfg or dfg
  target: cp # different target prediction
  processed_folder: '~/DGRL-Hardware/data_processed/'
  divide_seed: default #set as default or a seed
  raw_data_path: '~/DGRL-Hardware/data_raw/HLS/'
  data_processor: HLSDataProcessor

train:
  batch_size: 64
  epoch: 800
  optimizer: Adam
  scheduler: 
    name: StepLR
    step_size: 100
    gamma: 0.95
  lr : 0.0035306961942702117
  criterion: MSE
  wandb: 0
  train_files: '~/DGRL-Hardware/train_files/'
  directed: 0

model: 
  name: GCN
  hidden_dim: 56
  num_layers: 6
  node_input_dim: 7
  edge_input_dim: 2
  dropout: 0.1z
  mlp_out:
    num_layer: 3