# sample_config.yaml

utils:
  seed: 123
  torch_num_threads: 10

task:
  name: 'HLS'
  type: cdfg # type: cdfg or dfg
  target: cp # different target prediction
  processed_folder: '~/DGRL-Hardware/data_processed/'
  divide_seed: default #set as default or a seed
  raw_data_path: '~/DGRL-Hardware/data_raw/HLS/'
  data_processor: HLSDataProcessor

train:
  batch_size: 128
  epoch: 1000
  optimizer: Adam
  scheduler: 
    name: StepLR
    step_size: 100
    gamma: 0.95
  lr : 0.0014344013755033375
  criterion: MSE
  wandb: 0
  train_files: '~/DGRL-Hardware/train_files/'
  directed: 0

model: 
  name: MSGNN
  hidden_dim: 56
  num_layers: 5
  node_input_dim: 7
  edge_input_dim: 2
  dropout: 0
  mlp_out:
    num_layer: 3