# for HLS hidden_dim: [4,15]
name: BIGCN
hidden_dim: [2,7]
num_layers: [3,8]
# for HLS lr: [1e-4, 5e-3]
lr: [1e-4, 1e-2]
batch_size: [64, 128, 256, 512, 1024]
dropout: [0, 0.1, 0.2, 0.3]
# for HLS node_input_dim: 7
pe_dim_input: 20
pe_dim_output: 8

mlp_out:
  num_layer: [2,5]

# LS task only
sequence_hidden_dim: 20
sequence_input_dim: 10
num_node: 1045

# SR task only
num_class: 3